import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Carrito de Compras - Moskow Commerce",
  description: "Generated by Moskow Group",
};

export default function CarritoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8">
      <main className="flex-grow">
        {children}
      </main>
    </div>
  );
}
