"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Link from "next/link";

import { getProducts } from "@/services/dashboard/productoService";
import { getCategorias } from "@/services/dashboard/categoriaService";

// export const metadata = {
//   title: "Moskow Commerce - Página Principal",
//   description: "Generated by Moskow Group",
// };

export default function Home() {
  interface Categoria {
    id: number;
    name: string;
    description: string;
    creationDate: string;
    modificationDate: string;
    archivedDate: string;
  }

  const [categorias, setCategorias] = useState<Categoria[]>([]);

  useEffect(() => {
    async function fetchCategorias() {
      const response = await getCategorias();
      console.log(response);
      setCategorias(response.data);
    }
    fetchCategorias();
  }, []);

  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-grow">
        <section
          className="py-12 md:py-24 custom-bg relative"
          style={{
            backgroundImage: "url('/mate-unsplash.jpg')",
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          <div
            className="absolute inset-0 bg-black bg-opacity-20"
            style={{ backdropFilter: "blur(5px)" }}
          ></div>
          <div className="container relative mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto text-center">
              <h1 className="text-4xl font-extrabold text-gray-200 sm:text-5xl md:text-6xl">
                La mayor variedad de mates y bombillas de todo el país
              </h1>
              <p className="mt-4 text-xl text-gray-300">
                Descubrí nuestra selección de productos de calidad y disfrutá de un mate como nunca antes.
              </p>
              <div className="mt-8">
                <Button size="lg" className="bg-gray-200 text-gray-800 hover:text-white">
                  Comprar
                </Button>
              </div>
            </div>
          </div>
        </section>

        <section className="py-12">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <h2 className="text-3xl font-bold text-gray-900 mb-8">
              Categorías
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              {categorias.map((category) => (
                <div
                  key={category.id}
                  className="group relative overflow-hidden rounded-lg shadow-md"
                >
                  <img
                    src={`/placeholder.svg?height=300&width=400`}
                    alt={category.name}
                    className="w-full h-48 object-cover transition-transform group-hover:scale-105"
                  />
                  <div className="absolute inset-0 bg-black bg-opacity-40 flex items-center justify-center">
                    <h3 className="text-white text-xl font-semibold">
                      {category.name}
                    </h3>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="py-12 bg-gray-50">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <h2 className="text-3xl font-bold text-gray-900 mb-8">
              Productos
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[1, 2, 3, 4].map((product) => (
                <div
                  key={product}
                  className="bg-white rounded-lg shadow-md overflow-hidden"
                >
                  <img
                    src={`/placeholder.svg?height=300&width=400`}
                    alt={`Product ${product}`}
                    className="w-full h-48 object-cover"
                  />
                  <div className="p-4">
                    <h3 className="text-lg font-semibold mb-2">
                      Product {product}
                    </h3>
                    <p className="text-gray-600 mb-4">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    </p>
                    <div className="flex items-center justify-between">
                      <span className="text-xl font-bold text-primary">
                        $99.99
                      </span>
                      <Button variant="outline">Add to Cart</Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
